dist: xenial
language: python
python:
  - "3.6"

branches:
  only:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_${HUGO_VER}_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - pip install Pygments


script:
  - hugo
  # - ./deploy.sh
  # - git push -f https://${GH_TOKEN}@github.com/${GH_REPO}.git $(GITHUB_PAGES_BRANCH)

env:
  global:
    - HUGO_VER: "0.63.1"
    # - GH_REPO: brillliantz/mysite
    # - GITHUB_PAGES_BRANCH: gh-pages

deploy:
  provider: pages
  local_dir: public
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the repo settings page on TravisCI
  keep_history: false
  on:
    branch: master
    
