language: python

python:
    - "2.7"

branches:
  only:
  - master

before_install: "pip install -r requirements_0.txt"

install: "pip install -r requirements.txt"

before_script:
- pelican-themes -i ./theme/elegant

script:
- make github

env:
  global:
      - GH_REPO: brillliantz/mysite
      - secure: "qomLrQrsddQiwt91WNAp8snj7sVzZbdYe9yrX+TzP1yWYTPvNNFDSG5JWLz3OyQ0ipD0SnGcGOF+2jZWzKzWB/KEOCLyGAYRQPC9vAmdzt0OH28dZ1l4UtdW3XruEYF1SomtmYnUTnR3gJD891EB2/QR6u6iW+Zt1ng02o8jfFt+1DCBMRmYKU/Mng78d0JGSHrgNKclkpFpHq8LD6WL2LrnCS1vKXSX+Iwa7gJZ9EueFV3gUDk41ad5ZeX9u3HKiU1uAymNtKu69Q9OPcqA7SAmqJaObtc+EgDNgKkRfKat1O3RwWcQOMnIvOnY/gfAa19t36xMBd4/3R5Y3fAQTqUtMn20Ga8kOgjC3G1bHoStuYEXLHqk3JpoMBjTZCjEaSUdtVZylhJMn9xJ/2IMuLxR0hYIO25zdkaARjmF8nQwMKcIzF894kR4GJtdBEWUUo2+d3YCx3yX9ijs03GHt9VEhFgDEVoZhbEbpWbaSJ4xQ6vmVZTg7zKxZFoFud/P4E6+zzyb6PPU98Rp+IeidRueHIpjQQoed8SLQfP4WA3fipOn30OK549zWGPjm+e6QpuzDuceMDpKlrgqWv56WOn1EEGCIJavtMNXeubhGgVXVIS+9Gu3gUCnTPNazRWPOLATrNg32Nu4q6HOGj0qayOwZjygiZQ+IhAJt/AOcdQ="
