title = "Bingnan's Blog"
baseURL = "https://brillliantz.github.io/mysite/"
languageCode = "zh-cn"
theme = "ananke"
summaryLength = 140
hasCJKLanguage = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

disqusShortname = "bnliu"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Read, Think, Write."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/brillliantz"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/bingnliu"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6
  
  commentoEnable = true
  show_reading_time = true
  toc = true
  featured_image = "/images/RYBWnB.jpg"
  cover_dimming_class = "bg-black-20"

permalinks = "/:year/:month/:title/"
