title = "Bingnan's Blog"
baseURL = "https://brillliantz.github.io/mysite/"
languageCode = "en"
theme = "ananke"
summaryLength = 140
hasCJKLanguage = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "UA-157119715-1"
enableRobotsTXT = true

disqusShortname = "bnliu"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  body_classes = "helvetica bg-near-white"
  mainSections = ["SelfDevelopment", "PeriodicalReflection", "Quant", "Coding"]
  custom_css = ["/css/custom.css"]
  favicon = "mysite/favicon.ico"
  description = "Read, Think, Write."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/brillliantz"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/bingnliu"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6
  
  commentoEnable = true
  show_reading_time = true
  toc = true
  featured_image = "/images/RYBWnB.svg"
  cover_dimming_class = "bg-black-0"

[permalinks]
